L = {} -- Polish Content Strings by meerfi

///////////////////// -- [[ InterOps Weapons ]] --
-- Weapons
ws = "tacrp_io_"
w = ws .. "870"
-- L["wep." .. w .. ".name.full"] = "Remington 870 SPMM"
-- L["wep." .. w .. ".name"] = "R870 SPMM"
L["wep." .. w .. ".desc"] = "Strzelba \"Marine Magnum\" pokryta niklem. Słaba obsługa, ale ma dużą pojemność i moc ognia."
L["wep." .. w .. ".desc.quote"] = "\"JEST ZŁOTO W TYCH WZGÓRZACH!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Remington"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Millenia \nSounds: Vunsunta, xLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "ab10"
-- L["wep." .. w .. ".name.full"] = "Intratec AB-10"
-- L["wep." .. w .. ".name"] = "AB-10"
L["wep." .. w .. ".desc"] = "Półautomatyczny model \"After Ban\" TEC-9 z krótką, nietokowaną lufą. Duży magazynek, ale niewiarygodny."
L["wep." .. w .. ".desc.quote"] = "\"Kto potrzebuje broni szturmowej?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Intratec"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Payday 2 \nSounds: The_AntiPirate \nAnimations: Tactical Intervention"

w = ws .. "af2011"
-- L["wep." .. w .. ".name.full"] = "AF2011-A1"
-- L["wep." .. w .. ".name"] = "AF2011"
L["wep." .. w .. ".desc"] = "W zasadzie dwa połączone pistolety M1911, ta egzotyczna abominacja strzela dwiema kulami przy każdym pociągnięciu spustu."
L["wep." .. w .. ".desc.quote"] = "\"Jeśli 1911 jest tak dobry, dlaczego nie ma 1911 2?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Arsenal Firearms"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "automag"
-- L["wep." .. w .. ".name.full"] = "Auto Mag Pistol"
-- L["wep." .. w .. ".name"] = "Auto Mag"
L["wep." .. w .. ".desc"] = "Wysoce precyzyjny pistolet magnum. Świetne prowadzenie dzięki swojemu rozmiarowi, ale może montować tylko optykę pistoletową."
L["wep." .. w .. ".desc.quote"] = "Przeklęty design, który zdołał większość swoich producentów."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Auto Mag Corporation"
-- L["wep." .. w .. ".credits"] = "Model: RedRogueXIII \nTextures/Sounds: Futon \nAnimations: Tactical Intervention"

w = ws .. "chinalake"
-- L["wep." .. w .. ".name.full"] = "China Lake Launcher"
-- L["wep." .. w .. ".name"] = "China Lake"
L["wep." .. w .. ".desc"] = "Ciężki granatnik o działaniu pompowym z wysoką prędkością początkową, ale słabą obsługą."
L["wep." .. w .. ".desc.quote"] = "Tylko 59 takich kiedykolwiek istniało. Skąd masz ten jeden?"
-- L["wep." .. w .. ".trivia.manufacturer"] = "NAWS China Lake"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "coltsmg"
-- L["wep." .. w .. ".name.full"] = "Colt 9mm SMG"
-- L["wep." .. w .. ".name"] = "Colt SMG"
L["wep." .. w .. ".desc"] = "SMG na platformie AR z ogniem seryjnym. Doskonała kontrola odrzutu, dobre obrażenia i zasięg, ale ograniczone opcje optyczne. Faworyzowany przez Departament Energii."
L["wep." .. w .. ".desc.quote"] = "Głośnik nie jest w zestawie."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Assets: Twinke Masta & Kimono \nSounds: Strelok & New World Interactive \nAnimations: Tactical Intervention"

w = ws .. "cx4"
-- L["wep." .. w .. ".name.full"] = "Beretta CX4 Storm"
-- L["wep." .. w .. ".name"] = "CX4 Storm"
L["wep." .. w .. ".desc"] = "Półautomatyczna karabinek pistoletowy o dobrym zasięgu. Przeciętna penetracja pancerza, ale duża rama sprawia, że broń jest bardzo stabilna."
L["wep." .. w .. ".desc.quote"] = "\"Jak powszechnie wiadomo, w arsenale pewnego lidera PMC.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "degala"
-- L["wep." .. w .. ".name.full"] = "Desert Eagle"
-- L["wep." .. w .. ".name"] = "Deagle"
L["wep." .. w .. ".desc"] = "Imponujący pistolet magnum, tak ikoniczny, jak to tylko możliwe.\nPotężny i o dużej pojemności, ale odrzut jest trudny do opanowania."
L["wep." .. w .. ".desc.quote"] = "\"Słyszysz to, Mr. Anderson?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Magnum Research"
-- L["wep." .. w .. ".credits"] = "Model: Vashts1985 \nTextures: Racer445 \nSounds:Vunsunta, XLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "fiveseven"
-- L["wep." .. w .. ".name.full"] = "FN Five-seveN"
-- L["wep." .. w .. ".name"] = "Five-seveN"
L["wep." .. w .. ".desc"] = "Masywny pistolet kal. PDW o doskonałej pojemności.\nPociski o wysokiej prędkości zachowują skuteczność na dystansie i łatwo przebijają pancerz."
L["wep." .. w .. ".desc.quote"] = "Czy to fretka biega wokół?"
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2, edited by speedonerd \nSounds: Vunsunta, Counter-Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "fnc"
-- L["wep." .. w .. ".name.full"] = "FN FNC Para"
-- L["wep." .. w .. ".name"] = "FNC Para"
L["wep." .. w .. ".desc"] = "Lekki karabin szturmowy z wysoką precyzją strzałów z biodra i mobilnością, ale niskim zasięgiem i słabą penetracją pancerza."
L["wep." .. w .. ".desc.quote"] = "\"Mówię, co myślę i robię, co mówię.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Twinke Masta, the_tub,  Xero \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "glock18"
-- L["wep." .. w .. ".name"] = "Glock 18C"
L["wep." .. w .. ".desc"] = "Pistolet maszynowy o wysokiej szybkostrzelności i mobilności."
L["wep." .. w .. ".desc.quote"] = "\"Sooner or later, you'll have to jump.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Glock Ges.m.b.H"
-- L["wep." .. w .. ".credits"] = "Model: Hav0k101 \nTextures: el maestro de graffiti \nSounds: BlitzBoaR, Lorn, Ghost597879, Zeven II \nAnimations: Tactical Intervention"

w = ws .. "k98"
-- L["wep." .. w .. ".name.full"] = "Karabiner 98k"
-- L["wep." .. w .. ".name"] = "Kar98k"
L["wep." .. w .. ".desc"] = "Zabytkowy karabin z zamkiem czterotaktowym o trwałej konstrukcji. Potężny z bliska, ale zasadniczo przestarzały na współczesnym polu bitwy."
L["wep." .. w .. ".desc.quote"] = "\"Chcesz totalnej wojny?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Mauser"
-- L["wep." .. w .. ".credits"] = "Model: Day of Defeat: Source, edited by 8Z \nTextures: Cafe Rev., rascal, 5hifty \nSounds: rzen1th \nAnimations Cry of Fear, Lazarus"

w = ws .. "k98_varmint"
-- L["wep." .. w .. ".name"] = "Varmint Rifle"
L["wep." .. w .. ".desc"] = "Karabin powtarzalny oparty na mechanizmie Mausera. Akceptuje wszechobecne magazynki AR-15. Lekki, łatwy w obsłudze i ma dużą pojemność, ale obrażenia są niskie."
L["wep." .. w .. ".desc.quote"] = "Dla gryzoni... niepozornych rozmiarów."
-- L["wep." .. w .. ".trivia.manufacturer"] = "All-American Firearms"
-- L["wep." .. w .. ".credits"] = "Model: Day of Defeat: Source, edited by 8Z \nTextures: 5hifty \nSounds: rzen1th \nAnimations: Tactical Intervention"

w = ws .. "m14"
-- L["wep." .. w .. ".name"] = "M14 SOPMOD"
L["wep." .. w .. ".desc"] = "Zmodernizowany karabin z krótką lufą o poprawionej mobilności i szybkostrzelności automatycznej, ale z dużym odrzutem.\nWyposażony w celownik 6x."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Troy Industries"
-- L["wep." .. w .. ".credits"] = "Model: General Tso & Twinke Masta \nTextures: Thanez, Twinke Masta \nSounds: Lakedown, teh strelok & Futon \nAnimations: Tactical Intervention"

w = ws .. "m16a2"
-- L["wep." .. w .. ".name.full"] = "Colt M16A2"
-- L["wep." .. w .. ".name"] = "M16A2"
L["wep." .. w .. ".desc"] = "Stary karabin szturmowy z ograniczonymi opcjami optyki. Mimo to, jego stabilny odrzut i wysokie obrażenia sprawiają, że jest niezawodny na średnim dystansie."
L["wep." .. w .. ".desc.quote"] = "\"Strzelaj czysto, obserwuj tło.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta, SureShot, vagrant \nTextures: Stoke, modderfreak \nSounds: Vunsunta, Navaro \nAnimations: Tactical Intervention"

w = ws .. "m500"
-- L["wep." .. w .. ".name.full"] = "SW Model 500"
-- L["wep." .. w .. ".name"] = "M500"
L["wep." .. w .. ".desc"] = "Masywny rewolwer o długiej lufie wystrzeliwujący potężny nabój magnum, uznawany za najpotężniejszy pistolet produkcyjny na świecie."
L["wep." .. w .. ".desc.quote"] = "\"Wy, idioci, zrujnowaliście pięcioletnie śledztwo!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
-- L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nOriginally ported to CS 1.6 by GR_Lucia \nSounds: Ghost597879, MSKyuuni & Zira \nAnimations: Tactical Intervention"

w = ws .. "mx4"
-- L["wep." .. w .. ".name.full"] = "Beretta MX4 Storm"
-- L["wep." .. w .. ".name"] = "MX4 Storm"
L["wep." .. w .. ".desc"] = "Wojskowy karabinek pistoletowy o wysokiej szybkostrzelności.\nPrzeciętna penetracja pancerza, ale duża rama sprawia, że broń jest dość stabilna."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "p226"
-- L["wep." .. w .. ".name.full"] = "SIG P226"
-- L["wep." .. w .. ".name"] = "P226"
L["wep." .. w .. ".desc"] = "Pistolet z doskonałym zasięgiem i precyzją, ale niskimi obrażeniami ogólnymi."
L["wep." .. w .. ".desc.quote"] = "\"Poprawny termin to 'laski', proszę pana.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Model: SoulSlayer \nTextures: Thanez \nSounds: Anders, DMG, FxDarkloki, & Thanez \nAnimations: Tactical Intervention"

w = ws .. "rpk"
-- L["wep." .. w .. ".name"] = "RPK"
L["wep." .. w .. ".desc"] = "Lekki karabin maszynowy pochodzący od karabinu piechoty. Wysoka siła rażenia i dobry odrzut, ale słaba mobilność i rozrzut."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Molot"
-- L["wep." .. w .. ".credits"] = "Assets: Call To Arms \nAnimations: Tactical Intervention"

w = ws .. "ruger"
-- L["wep." .. w .. ".name.full"] = "AWC Amphibian Ruger"
-- L["wep." .. w .. ".name"] = "Amphibian"
L["wep." .. w .. ".desc"] = "Pistolet małego kalibru wyposażony w zintegrowany tłumik. Prawie zerowy odrzut ze względu na słabe naboje."
L["wep." .. w .. ".desc.quote"] = "\"Ciesz się, że nigdy nie miałeś wyboru.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Sturm, Ruger & Co."
-- L["wep." .. w .. ".credits"] = "Model: The Lama \nTextures: The Miller \nAnimations: Tactical Intervention"

w = ws .. "saiga"
-- L["wep." .. w .. ".name"] = "Saiga-12K"
L["wep." .. w .. ".desc"] = "Strzelba o dużej pojemności zasilana z magazynka pudełkowego. Ciasny rozrzut i wysoka szybkostrzelność, ale obrażenia są stosunkowo niskie."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kalashnikov Concern"
-- L["wep." .. w .. ".credits"] = "Assets: Battlefield 3 \nAnimations: Tactical Intervention"

w = ws .. "scarh"
-- L["wep." .. w .. ".name.full"] = "FN SCAR-H CQC"
-- L["wep." .. w .. ".name"] = "SCAR-H"
L["wep." .. w .. ".desc"] = "Kompaktowy, bardzo mobilny karabin bojowy z szybką obsługą."
L["wep." .. w .. ".desc.quote"] = "\"Sand Bravo, odczytujemy 70 celów w twoim sektorze.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN America"
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2, edited by speedonerd \nAnimations: Tactical Intervention"

w = ws .. "sg550"
-- L["wep." .. w .. ".name.full"] = "SIG SG 550-1 Sniper"
-- L["wep." .. w .. ".name"] = "SG 550-1"
L["wep." .. w .. ".desc"] = "Karabin wyborowy kaliberu karabinu z szybkim ogniem automatycznym. Łatwy do kontroli w krótkich seriach i ma wysoką penetrację pancerza. Domyślnie wyposażony w lunetę 6x."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c & Twinke Masta \nTextures: Twinke Masta \nSounds: Farion, Treyarch & Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "sg550r"
-- L["wep." .. w .. ".name.full"] = "SIG SG550-2 SP"
-- L["wep." .. w .. ".name"] = "SG 550-2"
L["wep." .. w .. ".desc"] = "Długi karabin przekształcony na półautomatyczny dla rynków cywilnych. Łatwy w obsłudze i ma wysoką penetrację pancerza."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c & Twinke Masta \nTextures: Twinke Masta \nSounds: Farion, Treyarch & Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "sl8"
-- L["wep." .. w .. ".name.full"] = "HK SL8"
-- L["wep." .. w .. ".name"] = "SL8"
L["wep." .. w .. ".desc"] = "Półautomatyczna wersja G36 przeznaczona do precyzyjnego strzelania. Niska szybkostrzelność, ale kontrola odrzutu jest doskonała.\nWyposażony w celownik 2x, ale nie ma opcji celownika mechanicznego."
-- L["wep." .. w .. ".desc.quote"] = "\"Used to be a cop myself, only for one day though.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c \nTextures: Twinke Masta \nSounds: KingFriday \nAnimations: Tactical Intervention"

w = ws .. "star15"
-- L["wep." .. w .. ".name.full"] = "Spikes Tactical AR-15"
-- L["wep." .. w .. ".name"] = "ST AR-15"
L["wep." .. w .. ".desc"] = "Poprawiony karabin AR-15 z myślą o precyzyjnym strzelaniu. \nZawsze wybór samotników na ścieżce zemsty, twój los będzie hałaśliwym pogrzebem... i cichym pożegnaniem. Przynieś detonator."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Spikes Tactical"
-- L["wep." .. w .. ".credits"] = "Assets: carl ruins everything, Leon-DLL, Mira + various sources \nSounds: Insurgency, rzen1th & Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "t850"
-- L["wep." .. w .. ".name.full"] = "Taurus 850 Ultralite"
-- L["wep." .. w .. ".name"] = "T850"
L["wep." .. w .. ".desc"] = "Rewolwer z krótką lufą o kompaktowych wymiarach. Skuteczność gwałtownie spada poza zasięg punktowy."
-- L["wep." .. w .. ".desc.quote"] = "Cardio is free when you're chasing gangsters."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Taurus"
-- L["wep." .. w .. ".credits"] = "Model: Fearfisch \nTextures: Millenia \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "tec9"
-- L["wep." .. w .. ".name.full"] = "Intratec TEC-9"
-- L["wep." .. w .. ".name"] = "TEC-9"
L["wep." .. w .. ".desc"] = "Pistolet maszynowy o złej sławie ze względu na łatwość konwersji na pełny automat, a następnie kryminalne użycie."
L["wep." .. w .. ".desc.quote"] = "\"Klient ma zawsze rację.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Intratec"
-- L["wep." .. w .. ".credits"] = "Model & Texture: Payday 2 \nSounds: The_AntiPirate \nAnimations: Tactical Intervention"

w = ws .. "trg42"
-- L["wep." .. w .. ".name.full"] = "Sako TRG-42"
-- L["wep." .. w .. ".name"] = "TRG-42"
L["wep." .. w .. ".desc"] = "Karabin snajperski Magnum o przyzwoitej obsłudze i mobilności. \nPotężny, ale wolno się przeładowuje i nie jest bardzo stabilny. \nDomyślnie wyposażony w lunetę 12x."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SAKO"
-- L["wep." .. w .. ".credits"] = "Model: Darkstorn \nTextures: SilentAssassin12 \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "usc"
-- L["wep." .. w .. ".name.full"] = "HK USC"
-- L["wep." .. w .. ".name"] = "USC"
L["wep." .. w .. ".desc"] = "Półautomatyczna wersja karabinka UMP. Używa magazynków o niskiej pojemności, ale jego długa lufa i zespół chwytu zapewniają doskonałe osiągi na średnim dystansie."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Twinke Masta, xLongWayHome, Stoke, Teh Snake & Millenia etc. \nAnimations: Tactical Intervention"

w = ws .. "val"
-- L["wep." .. w .. ".name"] = "AS Val"
L["wep." .. w .. ".desc"] = "Karabin z integralnym tłumikiem o wysokim wyjściu obrażeń i precyzji, ale słabo radzi sobie przy długich seriach."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Model & Textures: S.T.A.L.K.E.R. \nSounds: S.T.A.L.K.E.R. & Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "vp70"
-- L["wep." .. w .. ".name.full"] = "HK VP70"
-- L["wep." .. w .. ".name"] = "VP70"
L["wep." .. w .. ".desc"] = "Pistolet polimerowy z innowacyjnym kolbą-holsterem, umożliwiającym niezwykle szybki ogień seriami."
-- L["wep." .. w .. ".desc.quote"] = "\"Where's everyone going? Bingo?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model & Textures: KnechtRuprecht \nSounds: Strelok & xLongWayHome \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "vss"
-- L["wep." .. w .. ".name.full"] = "VSS Vintorez"
-- L["wep." .. w .. ".name"] = "Vintorez"
L["wep." .. w .. ".desc"] = "Karabin wyborowy z integralnym tłumikiem o wysokiej szybkostrzelności i niskim odrzucie, ale słabo radzi sobie w długich seriach. \nDomyślnie wyposażony w lunetę 6x."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Model: Ettubrutesbro, Millenia & Twinke Masta \nTextures: Millenia \nSounds: S.T.A.L.K.E.R. & Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "xm8car"
-- L["wep." .. w .. ".name.full"] = "HK XM8 Compact"
-- L["wep." .. w .. ".name"] = "XM8 Compact"
L["wep." .. w .. ".desc"] = "Eksperymentalny karabinek wielozadaniowy. Łatwy w użyciu, ale z niskimi obrażeniami. \nWyposażony w regulowany, zintegrowany celownik 2-8x."
-- L["wep." .. w .. ".desc.quote"] = "\"Who loves spaghetti?!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: End Of Days \nTextures: Copkiller, Twinke Masta & Wangchung \nAnimations: Tactical Intervention"

w = ws .. "xm8lmg"
-- L["wep." .. w .. ".name.full"] = "HK XM8 LMG"
-- L["wep." .. w .. ".name"] = "XM8 LMG"
L["wep." .. w .. ".desc"] = "Eksperymentalny karabin wielozadaniowy w konfiguracji MG. Lekki, o dużej pojemności i niskim odrzucie, ale słaba moc. \nPosiada regulowany wbudowany celownik 2-8x."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: End Of Days \nTextures: Copkiller, Twinke Masta & Wangchung \nAnimations: Tactical Intervention"

-- Attachments (interops)
-- L["att.ammo_star15_300blk.name.full"] = "ST AR-15 .300 AC Blackout Mod Kit"
-- L["att.ammo_star15_300blk.name"] = ".300 BLK"
-- L["att.ammo_star15_300blk.desc"] = "Modification to load lower velocity bullets with better CQB potential."

-- L["att.ammo_star15_50beo.name.full"] = "ST AR-15 .50 Beowulf Mod Kit"
-- L["att.ammo_star15_50beo.name"] = ".50 BEO"
-- L["att.ammo_star15_50beo.desc"] = "Modification to load low capacity, high power magnum rounds."

-- L["att.bolt_af2011_alt.name.full"] = "AF2011-A1 Alternating Bolt"
-- L["att.bolt_af2011_alt.name"] = "Alternating"
-- L["att.bolt_af2011_alt.desc"] = "Malicious interpretation of the concept of \"double-stacked magazines\"."

-- L["att.muzz_comp_io_m14.desc"] = "att.muzz_pistol_comp.desc"

-- L["att.muzz_tec9_shroud.name.full"] = "TEC-9 Barrel Shroud"
-- L["att.muzz_tec9_shroud.name"] = "Shroud"
-- L["att.muzz_tec9_shroud.desc"] = "Barrel extension improving performance at range."

-- L["att.optic_ak_pso1.name.full"] = "PSO-1 Scope"
-- L["att.optic_ak_pso1.name"] = "PSO-1"
-- L["att.optic_ak_pso1.desc"] = "Russian dovetail scope with medium-long range magnification."

-- L["att.optic_ar_colt.name.full"] = "Colt 3x20 Scope"
-- L["att.optic_ar_colt.name"] = "Colt 3x20"
-- L["att.optic_ar_colt.desc"] = "Low power optical scope mounted on AR pattern carry handles."

-- L["att.optic_k98_zf41.name.full"] = "Zeiss 6x38 Scope"
-- L["att.optic_k98_zf41.name"] = "Zeiss"
-- L["att.optic_k98_zf41.desc"] = "Medium-power sniper scope made specially for the Kar98k."

-- L["att.optic_xm8_4x.name.full"] = "XM8 Integrated Scope (4x)"
-- L["att.optic_xm8_4x.name"] = "4x"
-- L["att.optic_xm8_4x.desc"] = "Medium range zoom setting with ACOG reticle."

-- L["att.optic_xm8_6x.name.full"] = "XM8 Integrated Scope (6x)"
-- L["att.optic_xm8_6x.name"] = "6x"
-- L["att.optic_xm8_6x.desc"] = "Medium-long range zoom setting with Short Dot reticle."

-- L["att.optic_xm8_8x.name.full"] = "XM8 Integrated Scope (8x)"
-- L["att.optic_xm8_8x.name"] = "8x"
-- L["att.optic_xm8_8x.desc"] = "Long range zoom setting with sniper reticle."

-- L["att.trigger_vp70_auto.name.full"] = "VP-70 Auto Sear Stock"
-- L["att.trigger_vp70_auto.name"] = "Automatic"
-- L["att.trigger_vp70_auto.desc"] = "The engineers at H&K are frothing at their mouths as we speak."

-- L["att.trigger_vp70_semi.name.full"] = "VP-70 Remove Stock"
-- L["att.trigger_vp70_semi.name"] = "Stockless"
-- L["att.trigger_vp70_semi.desc"] = "Removes burst fire capability, improving handling and mobility."