L = {} -- Swedish Content Strings by Moka

///////////////////// -- [[ InterOps Weapons ]] --
-- Weapons
ws = "tacrp_io_"
w = ws .. "870"
L["wep." .. w .. ".name.full"] = "Remington 870 SPMM"
L["wep." .. w .. ".name"] = "R870 SPMM"
L["wep." .. w .. ".desc"] = "Nickelpläterad \"Marine Magnum\"-hagelbössa. Dålig hantering, men bra kapacitet och eldkraft."
L["wep." .. w .. ".desc.quote"] = "\"DET FINNS GULD I DEM DÄR KULLARNA!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Remington"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta \nTexturer: Millenia \nLjud: Vunsunta, xLongWayHome \nAnimationer: Tactical Intervention"

w = ws .. "ab10"
L["wep." .. w .. ".name.full"] = "Intratec AB-10"
L["wep." .. w .. ".name"] = "AB-10"
L["wep." .. w .. ".desc"] = "Halvautomatisk \"Efter Förbjud\"-modell av TEC-9:an med en kort, icke-gängad pipa. Stort magasin men opålitlig."
L["wep." .. w .. ".desc.quote"] = "\"Vem behöver ett automatvapen?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Intratec"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Payday 2 \nLjud: The_AntiPirate \nAnimationer: Tactical Intervention"

w = ws .. "af2011"
L["wep." .. w .. ".name.full"] = "AF2011-A1"
L["wep." .. w .. ".name"] = "AF2011"
L["wep." .. w .. ".desc"] = "Praktiskt taget två M1911-pistoler ihopsvetsade, detta exotiska monstret skjuter två skott per avtryck."
L["wep." .. w .. ".desc.quote"] = "\"Om nu 1911 var så bra, varför finns ingen 1911 2?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Arsenal Firearms"
L["wep." .. w .. ".credits"] = "Tillgångar: Counter Strike: Online 2 \nAnimationer: Tactical Intervention"

w = ws .. "automag"
L["wep." .. w .. ".name.full"] = "Auto Mag Pistol"
L["wep." .. w .. ".name"] = "Auto Mag"
L["wep." .. w .. ".desc"] = "Väldigt träffsäker magnum-pistol. Bra hantering tack vare dess storlek men kan endast montera pistolsikten."
L["wep." .. w .. ".desc.quote"] = "\"Om den används korrekt så kan ta bort fingeravtryck.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Auto Mag Corporation"
L["wep." .. w .. ".credits"] = "Modell: RedRogueXIII \nTexturer/Ljud: Futon \nAnimationer: Tactical Intervention"

w = ws .. "chinalake"
L["wep." .. w .. ".name.full"] = "\"China Lake\"-Kastare"
L["wep." .. w .. ".name"] = "China Lake"
L["wep." .. w .. ".desc"] = "Tung pumprepeter granatkastare med hög mynningshastighet men dålig hantering."
L["wep." .. w .. ".desc.quote"] = "Endast 59 av dessa finns. Hur fick du tag på den här?"
L["wep." .. w .. ".trivia.manufacturer"] = "NAWS China Lake"
L["wep." .. w .. ".credits"] = "Tillgångar: Counter Strike: Online 2 \nAnimationer: Tactical Intervention"

w = ws .. "coltsmg"
L["wep." .. w .. ".name.full"] = "Colt 9mm KPist."
L["wep." .. w .. ".name"] = "Colt KPist."
L["wep." .. w .. ".desc"] = "AR-plattform kulsprutepistol med salvoeld. Utmärkt rekylkontroll, bra skada och räckvidd, men begränsade sikteval. Gynnas av Institutionen av Energi."
L["wep." .. w .. ".desc.quote"] = "Högtalare ej inkluderad."
L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
L["wep." .. w .. ".credits"] = "Tillgångar: Twinke Masta & Kimono \nLjud: Strelok & New World Interactive \nAnimationer: Tactical Intervention"

w = ws .. "cx4"
L["wep." .. w .. ".name.full"] = "Beretta CX4 Storm"
L["wep." .. w .. ".name"] = "CX4 Storm"
L["wep." .. w .. ".desc"] = "Halvautomatisk pistolkarbin med bra räckvidd.\nMåttlig penetration, men den stora ramen gör vapnet ganska stabilt."
L["wep." .. w .. ".desc.quote"] = "Som känt sedd i en viss legosoldat ledares förråd."
L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
L["wep." .. w .. ".credits"] = "Tillgångar: Counter Strike: Online 2 \nAnimationer: Tactical Intervention"

w = ws .. "degala"
L["wep." .. w .. ".name.full"] = "Desert Eagle"
L["wep." .. w .. ".name"] = "Deagle"
L["wep." .. w .. ".desc"] = "Imponerande magnun-pistol, så ikonisk som den kan vara.\nKraftfull och hög kapacitet, men rekylen är svår att hantera."
L["wep." .. w .. ".desc.quote"] = "\"Hör du det där, Herr Anderson?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Magnum Research"
L["wep." .. w .. ".credits"] = "Modell: Vashts1985 \nTexturer: Racer445 \nLjud:Vunsunta, XLongWayHome \nAnimationer: Tactical Intervention"

w = ws .. "fiveseven"
L["wep." .. w .. ".name.full"] = "FN Five-seveN"
L["wep." .. w .. ".name"] = "Five-seveN"
L["wep." .. w .. ".desc"] = "Skrymmande PDW-kaliber pistol med utmärkt kapacitet. \nPatroner med hög hastighet behåller effektivitet vid räckvidd och penetrerar lätt rustning."
L["wep." .. w .. ".desc.quote"] = "Är det en tamiller som springer runt?"
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".credits"] = "Tillgångar: Counter-Strike: Online 2, redigerad av speedonerd \nLjud: Vunsunta, Counter-Strike: Online 2 \nAnimationer: Tactical Intervention"

w = ws .. "fnc"
L["wep." .. w .. ".name.full"] = "FN FNC Para"
L["wep." .. w .. ".name"] = "FNC Para"
L["wep." .. w .. ".desc"] = "Lätt automatkarbin med hög precision från höften och rörlighet, men låg räckvidd och dålig penetration av rustning."
L["wep." .. w .. ".desc.quote"] = "\"Jag säger det jag menar och jag gör det jag säger.\""
L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta \nTexturer: Twinke Masta, the_tub,  Xero \nLjud: Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "glock18"
L["wep." .. w .. ".name"] = "Glock 18C"
L["wep." .. w .. ".desc"] = "Automatpistol med hög eldhastighet och rörlighet."
L["wep." .. w .. ".desc.quote"] = "\"Förr eller senare får du hoppa.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Glock Ges.m.b.H"
L["wep." .. w .. ".credits"] = "Modell: Hav0k101 \nTexturer: el maestro de graffiti \nLjud: BlitzBoaR, Lorn, Ghost597879, Zeven II \nAnimationer: Tactical Intervention"

w = ws .. "k98"
L["wep." .. w .. ".name.full"] = "Karabiner 98k"
L["wep." .. w .. ".name"] = "Kar98k"
L["wep." .. w .. ".desc"] = "Antik cylinderrepetergevär med bestående design. Kraftfull på nära håll, men är praktiskt taget föråldrad på det moderna slagfältet."
L["wep." .. w .. ".desc.quote"] = "\"Vill du ha totalt krig?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Mauser"
L["wep." .. w .. ".credits"] = "Modell: Day of Defeat: Source, redigerad av 8Z \nTexturer: Cafe Rev., rascal, 5hifty \nLjud: rzen1th \nAnimations Cry of Fear, Lazarus"

w = ws .. "k98_varmint"
L["wep." .. w .. ".name"] = "Varmintgevär"
L["wep." .. w .. ".desc"] = "Cylinderrepetergevär baserad på Mauser-slutstycket. Använder AR-15-magasin. Lätt vikt, lätt att hantera och har generös kapacitet, men skadan är låg."
L["wep." .. w .. ".desc.quote"] = "Mot gnagare av... anspråkslös storlek."
L["wep." .. w .. ".trivia.manufacturer"] = "All-American Firearms"
L["wep." .. w .. ".credits"] = "Modell: Day of Defeat: Source, redigerad av 8Z \nTexturer: 5hifty \nLjud: rzen1th \nAnimationer: Tactical Intervention"

w = ws .. "m14"
L["wep." .. w .. ".name"] = "M14 SOPMOD"
L["wep." .. w .. ".desc"] = "Modernt gevär med kort pipa och förbättrad rörlighet och snabb automateld men bestraffande rekyl. \nUtrustat med ett 6x kikarsikte som standard."
L["wep." .. w .. ".trivia.manufacturer"] = "Troy Industries"
L["wep." .. w .. ".credits"] = "Modell: General Tso & Twinke Masta \nTexturer: Thanez, Twinke Masta \nLjud: Lakedown, teh strelok & Futon \nAnimationer: Tactical Intervention"

w = ws .. "m16a2"
L["wep." .. w .. ".name.full"] = "Colt M16A2"
L["wep." .. w .. ".name"] = "M16A2"
L["wep." .. w .. ".desc"] = "Gammaldags automatkarbin med salvoeld och begränsade sikte alternativ. Trots det så gör dess stabila rekyl och höga skadan den pålitlig på medelavstånd."
L["wep." .. w .. ".desc.quote"] = "\"Ta klara skott, håll koll på bakgrunden.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
L["wep." .. w .. ".credits"] = "Modell: Twinke Masta, SureShot, vagrant \nTexturer: Stoke, modderfreak \nLjud: Vunsunta, Navaro \nAnimationer: Tactical Intervention"

w = ws .. "m500"
L["wep." .. w .. ".name.full"] = "SW Model 500"
L["wep." .. w .. ".name"] = "M500"
L["wep." .. w .. ".desc"] = "Stor revolver med lång pipa som skjuter en massiv magnum-kula. Sedd som världens mest kraftfulla produktions sidovapen."
L["wep." .. w .. ".desc.quote"] = "\"Ni dweebs förstörde precis en fem års utredning!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
L["wep." .. w .. ".credits"] = "Tillgångar: Alliance of Valiant Arms \nEgentligen portat till CS 1.6 av GR_Lucia \nLjud: Ghost597879, MSKyuuni & Zira \nAnimationer: Tactical Intervention"

w = ws .. "mx4"
L["wep." .. w .. ".name.full"] = "Beretta MX4 Storm"
L["wep." .. w .. ".name"] = "MX4 Storm"
L["wep." .. w .. ".desc"] = "Stor pistolkarbin med hög eldhastighet men måttlig penetrationsförmåga."
L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
L["wep." .. w .. ".credits"] = "Tillgångar: Counter Strike: Online 2 \nAnimationer: Tactical Intervention"

w = ws .. "p226"
L["wep." .. w .. ".name.full"] = "SIG P226"
L["wep." .. w .. ".name"] = "P226"
L["wep." .. w .. ".desc"] = "Sidovapen med överlägsen räckvidd och precision, men låg kapacitet."
L["wep." .. w .. ".desc.quote"] = "\"Korrekta talesättet är 'babes', sir.\""
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
L["wep." .. w .. ".credits"] = "Modell: SoulSlayer \nTexturer: Thanez \nLjud: Anders, DMG, FxDarkloki, & Thanez \nAnimationer: Tactical Intervention"

w = ws .. "rpk"
L["wep." .. w .. ".name"] = "RPK"
L["wep." .. w .. ".desc"] = "Lätt kulspruta härledd från ett infanterigevär. Hög skada och god rekyl, men dålig rörlighet och spridning."
L["wep." .. w .. ".trivia.manufacturer"] = "Molot"
L["wep." .. w .. ".credits"] = "Tillgångar: Call To Arms \nAnimationer: Tactical Intervention"

w = ws .. "ruger"
L["wep." .. w .. ".name.full"] = "AWC Amphibian Ruger"
L["wep." .. w .. ".name"] = "Amphibian"
L["wep." .. w .. ".desc"] = "Liten kaliber pistol utrustat med inbyggd ljuddämpare. Nästan ingen rekyl tack vare svaga patroner."
L["wep." .. w .. ".desc.quote"] = "\"Ta det lugnt i att du vet att jag inte hade något val.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Sturm, Ruger & Co."
L["wep." .. w .. ".credits"] = "Modell: The Lama \nTexturer: The Miller \nAnimationer: Tactical Intervention"

w = ws .. "saiga"
L["wep." .. w .. ".name"] = "Saiga-12K"
L["wep." .. w .. ".desc"] = "Hög kapacitets hagelbössa som matas från ett lådmagasin, perfekt för att tömma ett rum."
L["wep." .. w .. ".trivia.manufacturer"] = "Kalashnikov Concern"
L["wep." .. w .. ".credits"] = "Tillgångar: Battlefield 3 \nAnimationer: Tactical Intervention"

w = ws .. "scarh"
L["wep." .. w .. ".name.full"] = "FN SCAR-H CQC"
L["wep." .. w .. ".name"] = "SCAR-H"
L["wep." .. w .. ".desc"] = "Kompakt stridsgevär med hög rörlighet och hantering."
L["wep." .. w .. ".desc.quote"] = "\"Sand Bravo, vi läser 70 kontakter i eran sektor.\""
L["wep." .. w .. ".trivia.manufacturer"] = "FN America"
L["wep." .. w .. ".credits"] = "Tillgångar: Counter-Strike: Online 2, redigerad av speedonerd \nAnimationer: Tactical Intervention"

w = ws .. "sg550"
L["wep." .. w .. ".name.full"] = "SIG SG 550-1 Krypskyttegevär"
L["wep." .. w .. ".name"] = "SG 550-1"
L["wep." .. w .. ".desc"] = "Karbinkaliber krypskyttegevär med snabb automateld. Lätt att kontrollera i korta salvor och har hög penetrationsförmåga. Utrustat med ett 6x kikarsikte som standard."
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
L["wep." .. w .. ".credits"] = "Modell: Hav0c & Twinke Masta \nTexturer: Twinke Masta \nLjud: Farion, Treyarch & Tactical Intervention \nAnimationer: Tactical Intervention"

w = ws .. "sg550r"
L["wep." .. w .. ".name.full"] = "SIG SG550-2 SP"
L["wep." .. w .. ".name"] = "SG 550-2"
L["wep." .. w .. ".desc"] = "Gevär med lång pipa konverterad till halvautomat för civila marknade. Lätt att kontrollera och har hög penetrationsförmåga."
L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
L["wep." .. w .. ".credits"] = "Modell: Hav0c & Twinke Masta \nTexturer: Twinke Masta \nLjud: Farion, Treyarch & Tactical Intervention \nAnimationer: Tactical Intervention"

w = ws .. "sl8"
L["wep." .. w .. ".name.full"] = "HK SL8"
L["wep." .. w .. ".name"] = "SL8"
L["wep." .. w .. ".desc"] = "Halvautomatisk variant av G36:an gjord för precisions-skytte. Låg eldhastighet, men rekylkontrollen är utmärkt. \nUtrustat med ett 2x sikte utan järn & korn alternativ."
L["wep." .. w .. ".desc.quote"] = "\"Brukade vara en snut jag med, men endast i en dag.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell: Hav0c \nTexturer: Twinke Masta \nLjud: KingFriday \nAnimationer: Tactical Intervention"

w = ws .. "star15"
L["wep." .. w .. ".name.full"] = "Spikes Tactical AR-15"
L["wep." .. w .. ".name"] = "ST AR-15"
L["wep." .. w .. ".desc"] = "Eftermarknads AR-15 fint anpassad för precisionsskytte. \nAlltid valet för ensamma jägare på hämndens väg, ditt öde kommer bli en illalåtande begravning... och ett tyst förväl. Ta med en detonator."
L["wep." .. w .. ".trivia.manufacturer"] = "Spikes Tactical"
L["wep." .. w .. ".credits"] = "Tillgångar: carl ruins everything, Leon-DLL, Mira + diverse källor \nLjud: Insurgency, rzen1th & Tactical Intervention \nAnimationer: Tactical Intervention"

w = ws .. "t850"
L["wep." .. w .. ".name.full"] = "Taurus 850 Ultralite"
L["wep." .. w .. ".name"] = "T850"
L["wep." .. w .. ".desc"] = "\"Snub-nose\"-revolver med kompakt formfaktor. Dödligheten faller snabbt efter skottet skjuts."
L["wep." .. w .. ".desc.quote"] = "Konditionsträningen är gratis när du jagar gangsters."
L["wep." .. w .. ".trivia.manufacturer"] = "Taurus"
L["wep." .. w .. ".credits"] = "Modell: Fearfisch \nTexturer: Millenia \nLjud: Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "tec9"
L["wep." .. w .. ".name.full"] = "Intratec TEC-9"
L["wep." .. w .. ".name"] = "TEC-9"
L["wep." .. w .. ".desc"] = "Automatpistol känd för dess lätta konvertering till automateld, och påföljd kriminell användning."
L["wep." .. w .. ".desc.quote"] = "\"Kunden har alltid rätt.\""
L["wep." .. w .. ".trivia.manufacturer"] = "Intratec"
L["wep." .. w .. ".credits"] = "Modell & Texturer: Payday 2 \nLjud: The_AntiPirate \nAnimationer: Tactical Intervention"

w = ws .. "trg42"
L["wep." .. w .. ".name.full"] = "Sako TRG-42"
L["wep." .. w .. ".name"] = "TRG-42"
L["wep." .. w .. ".desc"] = "Magnum-krypskyttegevär med måttlig hantering och rörlighet. \nKraftfull, men låg cykelhastighet och inte väldigt stabil. \nUtrustat med ett 12x kikarsikte som standard."
L["wep." .. w .. ".trivia.manufacturer"] = "SAKO"
L["wep." .. w .. ".credits"] = "Modell: Darkstorn \nTexturer: SilentAssassin12 \nLjud: Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "usc"
L["wep." .. w .. ".name.full"] = "HK USC"
L["wep." .. w .. ".name"] = "USC"
L["wep." .. w .. ".desc"] = "Halvautomatisk karbinversion av UMP:n. Använder låg kapacitetsmagasin, men dess långa pipa och hopsatta greppkolv erbjuder utmärkt medelräckvidd prestanda."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Tillgångar: Twinke Masta, xLongWayHome, Stoke, Teh Snake & Millenia etc. \nAnimationer: Tactical Intervention"

w = ws .. "val"
L["wep." .. w .. ".name"] = "AS Val"
L["wep." .. w .. ".desc"] = "Gevär med inbyggd ljuddämpare och hög skada och precision, men har dålig prestanda vid längre salvoeld."
L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
L["wep." .. w .. ".credits"] = "Modell & Texturer: S.T.A.L.K.E.R. \nLjud: S.T.A.L.K.E.R. & Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "vp70"
L["wep." .. w .. ".name.full"] = "HK VP70"
L["wep." .. w .. ".name"] = "VP70"
L["wep." .. w .. ".desc"] = "Pistol av polymer med innovativ hölsterkolv som tillåter otroligt snabb salvoeld."
L["wep." .. w .. ".desc.quote"] = "\"Vart är alla på väg? Bingo?\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell & Texturer: KnechtRuprecht \nLjud: Strelok & xLongWayHome \nAnimationer: Tactical Intervention, redigerad av speedonerd"

w = ws .. "vss"
L["wep." .. w .. ".name.full"] = "VSS Vintorez"
L["wep." .. w .. ".name"] = "Vintorez"
L["wep." .. w .. ".desc"] = "Krypskyttegevär med inbyggd ljuddämpare och hög eldhastighet med låg rekyl, men har dålig prestanda vid längre salvoeld. \nUtrustat med ett 6x kikarsikte som standard."
L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
L["wep." .. w .. ".credits"] = "Modell: Ettubrutesbro, Millenia & Twinke Masta \nTexturer: Millenia \nLjud: S.T.A.L.K.E.R. & Vunsunta \nAnimationer: Tactical Intervention"

w = ws .. "xm8car"
L["wep." .. w .. ".name.full"] = "HK XM8 Kompact"
L["wep." .. w .. ".name"] = "XM8 Kompact"
L["wep." .. w .. ".desc"] = "Experimentell mångsidig karbin. Lätt att hantera, men låg skada. \nHar justerbart inbyggt 2-8x sikte."
L["wep." .. w .. ".desc.quote"] = "\"Who loves spaghetti?!\""
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell: End Of Days \nTexturer: Copkiller, Twinke Masta & Wangchung \nAnimationer: Tactical Intervention"

w = ws .. "xm8lmg"
L["wep." .. w .. ".name.full"] = "HK XM8 KSP"
L["wep." .. w .. ".name"] = "XM8 KSP"
L["wep." .. w .. ".desc"] = "Experimentell mångsidig karbin konfigurerad som en kulspruta. Lätt, hög kapacitet och låg rekyl, men dålig skada. \nHar justerbart inbyggt 2-8x sikte."
L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
L["wep." .. w .. ".credits"] = "Modell: End Of Days \nTexturer: Copkiller, Twinke Masta & Wangchung \nAnimationer: Tactical Intervention"

-- Attachments (interops)
L["att.ammo_star15_300blk.name.full"] = "ST AR-15 .300 AC Blackout Modd Kit"
L["att.ammo_star15_300blk.name"] = ".300 BLK"
L["att.ammo_star15_300blk.desc"] = "Anpassning för att ladda lägre hastighetspatroner med högre potential på nära distans."

L["att.ammo_star15_50beo.name.full"] = "ST AR-15 .50 Beowulf Modd Kit"
L["att.ammo_star15_50beo.name"] = ".50 BEO"
L["att.ammo_star15_50beo.desc"] = "Anpassning för att ladda låg kapacitet, hög kraft magnum-patroner."

L["att.bolt_af2011_alt.name.full"] = "AF2011-A1 Omväxlande Slutstycke"
L["att.bolt_af2011_alt.name"] = "Omväxlande"
L["att.bolt_af2011_alt.desc"] = "Illvillig tolkning av konceptet för \"dubbelstaplat magasin\"."

L["att.muzz_comp_io_m14.desc"] = "att.muzz_pistol_comp.desc"

L["att.muzz_tec9_shroud.name.full"] = "TEC-9 Pipa med Skydd"
L["att.muzz_tec9_shroud.name"] = "Skydd"
L["att.muzz_tec9_shroud.desc"] = "Förlängd pipa som förbättrar prestandan på avstånd."

L["att.optic_ak_pso1.name.full"] = "PSO-1-Sikte"
L["att.optic_ak_pso1.name"] = "PSO-1"
L["att.optic_ak_pso1.desc"] = "Ryskt laxstjärt sikte med medel-lång avstånd magnifiering."

L["att.optic_ar_colt.name.full"] = "Colt 3x20-Sikte"
L["att.optic_ar_colt.name"] = "Colt 3x20"
L["att.optic_ar_colt.desc"] = "Riktmedel med låg kraft monterad på AR-plattform bärhandtag."

L["att.optic_k98_zf41.name.full"] = "Zeiss 6x38-Kikarsikte"
L["att.optic_k98_zf41.name"] = "Zeiss"
L["att.optic_k98_zf41.desc"] = "Medelkraft kikarsikte gjord specifikt till Kar98k."

L["att.optic_xm8_4x.name.full"] = "XM8 Inbyggt Sikte (4x)"
L["att.optic_xm8_4x.name"] = "4x"
L["att.optic_xm8_4x.desc"] = "Medelräckvidd zoominställning med ACOG-hårkors."

L["att.optic_xm8_6x.name.full"] = "XM8 Inbyggt Sikte (6x)"
L["att.optic_xm8_6x.name"] = "6x"
L["att.optic_xm8_6x.desc"] = "Medel-lång räckvidd zoominställning med \"Short Dot\"-hårkors."

L["att.optic_xm8_8x.name.full"] = "XM8 Inbyggt Sikte (8x)"
L["att.optic_xm8_8x.name"] = "8x"
L["att.optic_xm8_8x.desc"] = "Lång räckvidd zoominställning med kikarsikte hårkors."

L["att.trigger_vp70_auto.name.full"] = "VP-70 Automateld Kolv"
L["att.trigger_vp70_auto.name"] = "Automateld"
L["att.trigger_vp70_auto.desc"] = "Ingenjörerna på H&K har skum i munnen vid detta ögonblick."

L["att.trigger_vp70_semi.name.full"] = "VP-70 Ta Bort Kolv"
L["att.trigger_vp70_semi.name"] = "Kolvlös"
L["att.trigger_vp70_semi.desc"] = "Tar bort förmågan för salvoeld och förbättrar hantering och rörlighet."