L = {} -- Chinese Content Strings by 8Z

///////////////////// -- [[ InterOps Weapons ]] --
-- Weapons
ws = "tacrp_io_"
w = ws .. "870"
-- L["wep." .. w .. ".name.full"] = "Remington 870 SPMM"
-- L["wep." .. w .. ".name"] = "R870 SPMM"
-- L["wep." .. w .. ".desc"] = "Nickel plated \"Marine Magnum\" shotgun. Poor handling, but has great capacity and firepower."
-- L["wep." .. w .. ".desc.quote"] = "\"THERE'S GOLD IN THEM THAR HILLS!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Remington"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Millenia \nSounds: Vunsunta, xLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "ab10"
-- L["wep." .. w .. ".name.full"] = "Intratec AB-10"
-- L["wep." .. w .. ".name"] = "AB-10"
-- L["wep." .. w .. ".desc"] = "Semi-automatic \"After Ban\" model of the TEC-9 with a short, non-threaded barrel. Big magazine, but unreliable."
-- L["wep." .. w .. ".desc.quote"] = "\"Who needs an assault weapon?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Intratec"
-- L["wep." .. w .. ".credits"] = "Model & Textures: Payday 2 \nSounds: The_AntiPirate \nAnimations: Tactical Intervention"

w = ws .. "af2011"
-- L["wep." .. w .. ".name.full"] = "AF2011-A1"
-- L["wep." .. w .. ".name"] = "AF2011"
-- L["wep." .. w .. ".desc"] = "Effectively two M1911s welded together, this exotic abomination fires two bullets per trigger pull."
-- L["wep." .. w .. ".desc.quote"] = "\"If the 1911 is so good, why isn't there a 1911 2?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Arsenal Firearms"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "automag"
-- L["wep." .. w .. ".name.full"] = "Auto Mag Pistol"
-- L["wep." .. w .. ".name"] = "Auto Mag"
-- L["wep." .. w .. ".desc"] = "Highly accurate magnum pistol. Great handling due to its size, but can only mount pistol optics."
-- L["wep." .. w .. ".desc.quote"] = "\"And if properly used, it can remove the fingerprints.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Auto Mag Corporation"
-- L["wep." .. w .. ".credits"] = "Model: RedRogueXIII \nTextures/Sounds: Futon \nAnimations: Tactical Intervention"

w = ws .. "chinalake"
-- L["wep." .. w .. ".name.full"] = "China Lake Launcher"
-- L["wep." .. w .. ".name"] = "China Lake"
-- L["wep." .. w .. ".desc"] = "Heavy pump action grenade launcher with high muzzle velocity but poor handling."
-- L["wep." .. w .. ".desc.quote"] = "Only 59 of these ever existed. Where'd you get this one?"
-- L["wep." .. w .. ".trivia.manufacturer"] = "NAWS China Lake"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "coltsmg"
-- L["wep." .. w .. ".name.full"] = "Colt 9mm SMG"
-- L["wep." .. w .. ".name"] = "Colt SMG"
-- L["wep." .. w .. ".desc"] = "AR platform burst-fire SMG. Excellent recoil control, good damage and range but limited optic options. Favored by the Department of Energy."
-- L["wep." .. w .. ".desc.quote"] = "Loudspeaker not included."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Assets: Twinke Masta & Kimono \nSounds: Strelok & New World Interactive \nAnimations: Tactical Intervention"

w = ws .. "cx4"
-- L["wep." .. w .. ".name.full"] = "Beretta CX4 Storm"
-- L["wep." .. w .. ".name"] = "CX4 Storm"
-- L["wep." .. w .. ".desc"] = "Semi-automatic pistol carbine with good range. \nMediocre armor penetration, but the large frame makes the weapon quite stable."
-- L["wep." .. w .. ".desc.quote"] = "As famously seen in a certain PMC leader's arsenal."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "degala"
-- L["wep." .. w .. ".name.full"] = "Desert Eagle"
-- L["wep." .. w .. ".name"] = "Deagle"
-- L["wep." .. w .. ".desc"] = "Imposing magnum pistol, as iconic as it gets. \nPowerful and high capacity, but recoil is hard to manage."
-- L["wep." .. w .. ".desc.quote"] = "\"You hear that, Mr. Anderson?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Magnum Research"
-- L["wep." .. w .. ".credits"] = "Model: Vashts1985 \nTextures: Racer445 \nSounds:Vunsunta, XLongWayHome \nAnimations: Tactical Intervention"

w = ws .. "fiveseven"
-- L["wep." .. w .. ".name.full"] = "FN Five-seveN"
-- L["wep." .. w .. ".name"] = "Five-seveN"
-- L["wep." .. w .. ".desc"] = "Bulky PDW caliber pistol with excellent capacity. \nHigh velocity rounds retain effectiveness at range and pierces armor easily."
-- L["wep." .. w .. ".desc.quote"] = "Is that a ferret running around?"
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2, edited by speedonerd \nSounds: Vunsunta, Counter-Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "fnc"
-- L["wep." .. w .. ".name.full"] = "FN FNC Para"
-- L["wep." .. w .. ".name"] = "FNC Para"
-- L["wep." .. w .. ".desc"] = "Lightweight assault rifle with high hipfire precision and mobility, but low range and poor armor penetration."
-- L["wep." .. w .. ".desc.quote"] = "\"I say what I mean and I do what I say.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN Herstal"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta \nTextures: Twinke Masta, the_tub,  Xero \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "glock18"
-- L["wep." .. w .. ".name"] = "Glock 18C"
-- L["wep." .. w .. ".desc"] = "Machine pistol with high fire rate and mobility."
-- L["wep." .. w .. ".desc.quote"] = "\"Sooner or later, you'll have to jump.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Glock Ges.m.b.H"
-- L["wep." .. w .. ".credits"] = "Model: Hav0k101 \nTextures: el maestro de graffiti \nSounds: BlitzBoaR, Lorn, Ghost597879, Zeven II \nAnimations: Tactical Intervention"

w = ws .. "k98"
-- L["wep." .. w .. ".name.full"] = "Karabiner 98k"
-- L["wep." .. w .. ".name"] = "Kar98k"
-- L["wep." .. w .. ".desc"] = "Antique bolt-action rifle with an enduring design. Powerful up close, but is essentially obsolete on the modern battlefield."
-- L["wep." .. w .. ".desc.quote"] = "\"Do you want total war?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Mauser"
-- L["wep." .. w .. ".credits"] = "Model: Day of Defeat: Source, edited by 8Z \nTextures: Cafe Rev., rascal, 5hifty \nSounds: rzen1th \nAnimations Cry of Fear, Lazarus"

w = ws .. "k98_varmint"
-- L["wep." .. w .. ".name"] = "Varmint Rifle"
-- L["wep." .. w .. ".desc"] = "Bolt-action rifle based on the Mauser action. Accepts ubiquitous AR-15 magazines. Lightweight, easy to use and has a generous capacity, but damage is low."
-- L["wep." .. w .. ".desc.quote"] = "For rodents of... unassuming size."
-- L["wep." .. w .. ".trivia.manufacturer"] = "All-American Firearms"
-- L["wep." .. w .. ".credits"] = "Model: Day of Defeat: Source, edited by 8Z \nTextures: 5hifty \nSounds: rzen1th \nAnimations: Tactical Intervention"

w = ws .. "m14"
-- L["wep." .. w .. ".name"] = "M14 SOPMOD"
-- L["wep." .. w .. ".desc"] = "Modernized short barrel rifle with improved mobility and fast automatic fire but punishing recoil. \nEquipped with a 6x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Troy Industries"
-- L["wep." .. w .. ".credits"] = "Model: General Tso & Twinke Masta \nTextures: Thanez, Twinke Masta \nSounds: Lakedown, teh strelok & Futon \nAnimations: Tactical Intervention"

w = ws .. "m16a2"
-- L["wep." .. w .. ".name.full"] = "Colt M16A2"
-- L["wep." .. w .. ".name"] = "M16A2"
-- L["wep." .. w .. ".desc"] = "Vintage burst assault rifle with limited optic options. Despite this, its stable recoil and high damage makes it reliable at medium range."
-- L["wep." .. w .. ".desc.quote"] = "\"Take clean shots, watch your background.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Colt"
-- L["wep." .. w .. ".credits"] = "Model: Twinke Masta, SureShot, vagrant \nTextures: Stoke, modderfreak \nSounds: Vunsunta, Navaro \nAnimations: Tactical Intervention"

w = ws .. "m500"
-- L["wep." .. w .. ".name.full"] = "SW Model 500"
-- L["wep." .. w .. ".name"] = "M500"
-- L["wep." .. w .. ".desc"] = "Massive long barrel revolver firing a massive magnum round, reigning as the most powerful production handgun in the world."
-- L["wep." .. w .. ".desc.quote"] = "\"You dweebs just ruined a five year investigation!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Smith & Wesson"
-- L["wep." .. w .. ".credits"] = "Assets: Alliance of Valiant Arms \nOriginally ported to CS 1.6 by GR_Lucia \nSounds: Ghost597879, MSKyuuni & Zira \nAnimations: Tactical Intervention"

w = ws .. "mx4"
-- L["wep." .. w .. ".name.full"] = "Beretta MX4 Storm"
-- L["wep." .. w .. ".name"] = "MX4 Storm"
-- L["wep." .. w .. ".desc"] = "Bulky pistol carbine with high rate of fire but mediocre armor penetration."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Pietro Beretta"
-- L["wep." .. w .. ".credits"] = "Assets: Counter Strike: Online 2 \nAnimations: Tactical Intervention"

w = ws .. "p226"
-- L["wep." .. w .. ".name.full"] = "SIG P226"
-- L["wep." .. w .. ".name"] = "P226"
-- L["wep." .. w .. ".desc"] = "Handgun with superior range and precision but low capacity."
-- L["wep." .. w .. ".desc.quote"] = "\"The correct term is 'babes,' sir.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Model: SoulSlayer \nTextures: Thanez \nSounds: Anders, DMG, FxDarkloki, & Thanez \nAnimations: Tactical Intervention"

w = ws .. "rpk"
-- L["wep." .. w .. ".name"] = "RPK"
-- L["wep." .. w .. ".desc"] = "Light machine gun derived from an infantry rifle. High damage and good recoil, but mobility and spread is poor."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Molot"
-- L["wep." .. w .. ".credits"] = "Assets: Call To Arms \nAnimations: Tactical Intervention"

w = ws .. "ruger"
-- L["wep." .. w .. ".name.full"] = "AWC Amphibian Ruger"
-- L["wep." .. w .. ".name"] = "Amphibian"
-- L["wep." .. w .. ".desc"] = "Small caliber pistol fitted with an integrated suppressor. Near-zero recoil due to weak rounds."
-- L["wep." .. w .. ".desc.quote"] = "\"Take comfort in knowing you never had a choice.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Sturm, Ruger & Co."
-- L["wep." .. w .. ".credits"] = "Model: The Lama \nTextures: The Miller \nAnimations: Tactical Intervention"

w = ws .. "saiga"
-- L["wep." .. w .. ".name"] = "Saiga-12K"
-- L["wep." .. w .. ".desc"] = "High capacity shotgun feeding from a box magazine, suitable for spraying down a room."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Kalashnikov Concern"
-- L["wep." .. w .. ".credits"] = "Assets: Battlefield 3 \nAnimations: Tactical Intervention"

w = ws .. "scarh"
-- L["wep." .. w .. ".name.full"] = "FN SCAR-H CQC"
-- L["wep." .. w .. ".name"] = "SCAR-H"
-- L["wep." .. w .. ".desc"] = "Compact, high mobility battle rifle with swift handling."
-- L["wep." .. w .. ".desc.quote"] = "\"Sand Bravo, we're reading 70 bogeys in your sector.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "FN America"
-- L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2, edited by speedonerd \nAnimations: Tactical Intervention"

w = ws .. "sg550"
-- L["wep." .. w .. ".name.full"] = "SIG SG 550-1 Sniper"
-- L["wep." .. w .. ".name"] = "SG 550-1"
-- L["wep." .. w .. ".desc"] = "Carbine caliber marksman rifle with fast automatic fire. Easy to control in short bursts and has high armor penetration. Equipped with a 6x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c & Twinke Masta \nTextures: Twinke Masta \nSounds: Farion, Treyarch & Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "sg550r"
-- L["wep." .. w .. ".name.full"] = "SIG SG550-2 SP"
-- L["wep." .. w .. ".name"] = "SG 550-2"
-- L["wep." .. w .. ".desc"] = "Long barrel rifle converted to semi-automatic for civilian markets. Easy to control and has high armor penetration."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SIG Sauer AG"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c & Twinke Masta \nTextures: Twinke Masta \nSounds: Farion, Treyarch & Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "sl8"
-- L["wep." .. w .. ".name.full"] = "HK SL8"
-- L["wep." .. w .. ".name"] = "SL8"
-- L["wep." .. w .. ".desc"] = "Semi-automatic variant of the G36 made for precision shooting. Low fire rate, but recoil control is excellent. \nEquipped with a 2x scope but has no ironsight option."
-- L["wep." .. w .. ".desc.quote"] = "\"Used to be a cop myself, only for one day though.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: Hav0c \nTextures: Twinke Masta \nSounds: KingFriday \nAnimations: Tactical Intervention"

w = ws .. "star15"
-- L["wep." .. w .. ".name.full"] = "Spikes Tactical AR-15"
-- L["wep." .. w .. ".name"] = "ST AR-15"
-- L["wep." .. w .. ".desc"] = "Aftermarket AR-15 fine tuned for precision shooting. \nEver the choice for lone wolves on a path of revenge, your fate will be a cacophonous funeral... and a silent farewell. Bring a detonator."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Spikes Tactical"
-- L["wep." .. w .. ".credits"] = "Assets: carl ruins everything, Leon-DLL, Mira + various sources \nSounds: Insurgency, rzen1th & Tactical Intervention \nAnimations: Tactical Intervention"

w = ws .. "t850"
-- L["wep." .. w .. ".name.full"] = "Taurus 850 Ultralite"
-- L["wep." .. w .. ".name"] = "T850"
-- L["wep." .. w .. ".desc"] = "Snub-nosed revolver with compact form factor. Lethality falls off sharply past point blank."
-- L["wep." .. w .. ".desc.quote"] = "Cardio is free when you're chasing gangsters."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Taurus"
-- L["wep." .. w .. ".credits"] = "Model: Fearfisch \nTextures: Millenia \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "tec9"
-- L["wep." .. w .. ".name.full"] = "Intratec TEC-9"
-- L["wep." .. w .. ".name"] = "TEC-9"
-- L["wep." .. w .. ".desc"] = "Machine pistol notorious for its ease of conversion to fully automatic fire, and subsequent criminal usage."
-- L["wep." .. w .. ".desc.quote"] = "\"The customer is always right.\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Intratec"
-- L["wep." .. w .. ".credits"] = "Model & Texture: Payday 2 \nSounds: The_AntiPirate \nAnimations: Tactical Intervention"

w = ws .. "trg42"
-- L["wep." .. w .. ".name.full"] = "Sako TRG-42"
-- L["wep." .. w .. ".name"] = "TRG-42"
-- L["wep." .. w .. ".desc"] = "Magnum sniper rifle with decent handling and mobility. \nPowerful, but slow to cycle and not very stable. \nEquipped with a 12x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "SAKO"
-- L["wep." .. w .. ".credits"] = "Model: Darkstorn \nTextures: SilentAssassin12 \nSounds: Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "usc"
-- L["wep." .. w .. ".name.full"] = "HK USC"
-- L["wep." .. w .. ".name"] = "USC"
-- L["wep." .. w .. ".desc"] = "Semi-automatic carbine variant of the UMP. Uses low capacity magazines, but its long barrel and gripstock assembly provides excellent medium range performance."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Assets: Twinke Masta, xLongWayHome, Stoke, Teh Snake & Millenia etc. \nAnimations: Tactical Intervention"

w = ws .. "val"
-- L["wep." .. w .. ".name"] = "AS Val"
-- L["wep." .. w .. ".desc"] = "Integrally-suppressed rifle with high damage output and precision, but performs poorly over long bursts."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Model & Textures: S.T.A.L.K.E.R. \nSounds: S.T.A.L.K.E.R. & Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "vp70"
-- L["wep." .. w .. ".name.full"] = "HK VP70"
-- L["wep." .. w .. ".name"] = "VP70"
-- L["wep." .. w .. ".desc"] = "Polymer pistol with an innovative holster stock that allows for incredibly fast burst fire."
-- L["wep." .. w .. ".desc.quote"] = "\"Where's everyone going? Bingo?\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model & Textures: KnechtRuprecht \nSounds: Strelok & xLongWayHome \nAnimations: Tactical Intervention, edited by speedonerd"

w = ws .. "vss"
-- L["wep." .. w .. ".name.full"] = "VSS Vintorez"
-- L["wep." .. w .. ".name"] = "Vintorez"
-- L["wep." .. w .. ".desc"] = "Integrally-suppressed marksman rifle with high fire rate and low recoil, but performs poorly over long bursts. \nEquipped with a 6x scope by default."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Tula Arms Plant"
-- L["wep." .. w .. ".credits"] = "Model: Ettubrutesbro, Millenia & Twinke Masta \nTextures: Millenia \nSounds: S.T.A.L.K.E.R. & Vunsunta \nAnimations: Tactical Intervention"

w = ws .. "xm8car"
-- L["wep." .. w .. ".name.full"] = "HK XM8 Compact"
-- L["wep." .. w .. ".name"] = "XM8 Compact"
-- L["wep." .. w .. ".desc"] = "Experimental multi-purpose carbine. Easy to use, but low damage. \nHas an adjustable integrated 2-8x scope."
-- L["wep." .. w .. ".desc.quote"] = "\"Who loves spaghetti?!\""
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: End Of Days \nTextures: Copkiller, Twinke Masta & Wangchung \nAnimations: Tactical Intervention"

w = ws .. "xm8lmg"
-- L["wep." .. w .. ".name.full"] = "HK XM8 LMG"
-- L["wep." .. w .. ".name"] = "XM8 LMG"
-- L["wep." .. w .. ".desc"] = "Experimental multi-purpose carbine in MG configuration. Light, high capacity and low recoil, but damage is poor. \nHas an adjustable integrated 2-8x scope."
-- L["wep." .. w .. ".trivia.manufacturer"] = "Heckler & Koch"
-- L["wep." .. w .. ".credits"] = "Model: End Of Days \nTextures: Copkiller, Twinke Masta & Wangchung \nAnimations: Tactical Intervention"

-- Attachments (interops)
L["att.ammo_star15_300blk.name.full"] = "ST AR-15 .300 AAC Blackout 改装套件"
L["att.ammo_star15_300blk.name"] = ".300 BLK"
L["att.ammo_star15_300blk.desc"] = "装填低速但近距离效果更好的弹药。"

L["att.ammo_star15_50beo.name.full"] = "ST AR-15 .50 Beowulf 改装套件"
L["att.ammo_star15_50beo.name"] = ".50 BEO"
L["att.ammo_star15_50beo.desc"] = "装填低容量高伤害的马格南弹药。"

L["att.bolt_af2011_alt.name.full"] = "AF2011-A1 交替枪管"
L["att.bolt_af2011_alt.name"] = "交替"
L["att.bolt_af2011_alt.desc"] = "交替使用两根枪管。"

L["att.muzz_comp_io_m14.desc"] = "att.muzz_pistol_comp.desc"

L["att.muzz_tec9_shroud.name.full"] = "TEC-9 枪管护照"
L["att.muzz_tec9_shroud.name"] = ".300 护罩"
L["att.muzz_tec9_shroud.desc"] = "加长枪管提升中距离性能。"

L["att.optic_ak_pso1.name.full"] = "PSO-1 瞄准镜"
L["att.optic_ak_pso1.name"] = "PSO-1"
L["att.optic_ak_pso1.desc"] = "中远距离倍率的光学准镜，部分华约枪械可用。"

L["att.optic_ar_colt.name.full"] = "柯尔特 3x20 枪镜"
L["att.optic_ar_colt.name"] = "柯尔特 3x20"
L["att.optic_ar_colt.desc"] = "低倍率光学准镜，部分 AR 型号枪械可用。"

L["att.optic_k98_zf42.name.full"] = "寨斯 6x36 枪镜"
L["att.optic_k98_zf42.name"] = "寨斯"
L["att.optic_k98_zf42.desc"] = "Kar98k 专用的中倍光学准镜。"

L["att.optic_xm8_4x.name.full"] = "XM8 内置准镜（4倍）"
L["att.optic_xm8_4x.name"] = "4x"
L["att.optic_xm8_4x.desc"] = "中距离倍率，使用 ACOG 准心。"

L["att.optic_xm8_6x.name.full"] = "XM8 内置准镜（6倍）"
L["att.optic_xm8_6x.name"] = "6x"
L["att.optic_xm8_6x.desc"] = "中远距离倍率，使用短点准心。"

L["att.optic_xm8_8x.name.full"] = "XM8 内置准镜（8倍）"
L["att.optic_xm8_8x.name"] = "8x"
L["att.optic_xm8_8x.desc"] = "远距离倍率，使用狙击准心。"

L["att.trigger_vp70_auto.name.full"] = "VP-70 自动枪托"
L["att.trigger_vp70_auto.name"] = "自动"
L["att.trigger_vp70_auto.desc"] = "用这个把 H&K 的工程师气到口吐白沫。"

L["att.trigger_vp70_semi.name.full"] = "VP-70 无枪托"
L["att.trigger_vp70_semi.name"] = "无枪托"
L["att.trigger_vp70_semi.desc"] = "摘下枪托失去三连发功能，但提升机动性和操作速度。"